export type Realm = {
  realmName: string;
};

export const realms: Realm[] = [
  { realmName: "Aegwynn" },
  { realmName: "Aerie Peak" },
  { realmName: "Agamaggan" },
  { realmName: "Aggramar" },
  { realmName: "Alexstrasza" },
  { realmName: "Alleria" },
  { realmName: "Altar of Storms" },
  { realmName: "Alterac Mountains" },
  { realmName: "Anetheron" },
  { realmName: "Anub'arak" },
  { realmName: "Anvilmar" },
  { realmName: "Area 52" },
  { realmName: "Argent Dawn" },
  { realmName: "Archimonde" },
  { realmName: "Arthas" },
  { realmName: "Arygos" },
  { realmName: "Auchindoun" },
  { realmName: "Azgalor" },
  { realmName: "Azralon" },
  { realmName: "Azshara" },
  { realmName: "Azuremyst" },
  { realmName: "Baelgun" },
  { realmName: "Balnazzar" },
  { realmName: "Black Dragonflight" },
  { realmName: "Blackhand" },
  { realmName: "Blackrock" },
  { realmName: "Blackwing Lair" },
  { realmName: "Blade's Edge" },
  { realmName: "Bladefist" },
  { realmName: "Bleeding Hollow" },
  { realmName: "Blood Furnace" },
  { realmName: "Bloodhoof" },
  { realmName: "Bonechewer" },
  { realmName: "Burning Blade" },
  { realmName: "Burning Legion" },
  { realmName: "Chromaggus" },
  { realmName: "Cho'gall" },
  { realmName: "Coilfang" },
  { realmName: "Crushridge" },
  { realmName: "Daggerspine" },
  { realmName: "Dalaran" },
  { realmName: "Dalvengyr" },
  { realmName: "Dark Iron" },
  { realmName: "Dawnbringer" },
  { realmName: "Deathwing" },
  { realmName: "Demon Soul" },
  { realmName: "Dentarg" },
  { realmName: "Destromath" },
  { realmName: "Dethecus" },
  { realmName: "Detheroc" },
  { realmName: "Doomhammer" },
  { realmName: "Drakkari" },
  { realmName: "Durotan" },
  { realmName: "Duskwood" },
  { realmName: "Earthen Ring" },
  { realmName: "Eitrigg" },
  { realmName: "Elune" },
  { realmName: "Emerald Dream" },
  { realmName: "Eonar" },
  { realmName: "Eredar" },
  { realmName: "Executus" },
  { realmName: "Exodar" },
  { realmName: "Farstriders" },
  { realmName: "Fizzcrank" },
  { realmName: "Garithos" },
  { realmName: "Garona" },
  { realmName: "Garrosh" },
  { realmName: "Gallywix" },
  { realmName: "Galakrond" },
  { realmName: "Gnomeregan" },
  { realmName: "Goldrinn" },
  { realmName: "Gorefiend" },
  { realmName: "Gorgonnash" },
  { realmName: "Greymane" },
  { realmName: "Grizzly Hills" },
  { realmName: "Gul'dan" },
  { realmName: "Gurubashi" },
  { realmName: "Haomarush" },
  { realmName: "Hakkar" },
  { realmName: "Hellscream" },
  { realmName: "Hyjal" },
  { realmName: "Icecrown" },
  { realmName: "Illidan" },
  { realmName: "Jaedenar" },
  { realmName: "Kael'thas" },
  { realmName: "Kalecgos" },
  { realmName: "Kargath" },
  { realmName: "Kel'Thuzad" },
  { realmName: "Khadgar" },
  { realmName: "Kil'jaeden" },
  { realmName: "Kilrogg" },
  { realmName: "Kirin Tor" },
  { realmName: "Korgath" },
  { realmName: "Kul Tiras" },
  { realmName: "Laughing Skull" },
  { realmName: "Lethon" },
  { realmName: "Lightning's Blade" },
  { realmName: "Lightninghoof" },
  { realmName: "Llane" },
  { realmName: "Lothar" },
  { realmName: "Maelstrom" },
  { realmName: "Magtheridon" },
  { realmName: "Madoran" },
  { realmName: "Malfurion" },
  { realmName: "Mal'Ganis" },
  { realmName: "Malygos" },
  { realmName: "Mannoroth" },
  { realmName: "Medivh" },
  { realmName: "Misha" },
  { realmName: "Moonrunner" },
  { realmName: "Muradin" },
  { realmName: "Nathrezim" },
  { realmName: "Nazgrel" },
  { realmName: "Nazjatar" },
  { realmName: "Nemesis" },
  { realmName: "Nesingwary" },
  { realmName: "Nordrassil" },
  { realmName: "Norgannon" },
  { realmName: "Onyxia" },
  { realmName: "Proudmoore" },
  { realmName: "Quel'dorei" },
  { realmName: "Quel'Thalas" },
  { realmName: "Ragnaros" },
  { realmName: "Ravencrest" },
  { realmName: "Ravenholdt" },
  { realmName: "Rexxar" },
  { realmName: "Runetotem" },
  { realmName: "Sargeras" },
  { realmName: "Scilla" },
  { realmName: "Sen'jin" },
  { realmName: "Sentinels" },
  { realmName: "Shadowmoon" },
  { realmName: "Shattered Hand" },
  { realmName: "Shattered Halls" },
  { realmName: "Silver Hand" },
  { realmName: "Sisters of Elune" },
  { realmName: "Skullcrusher" },
  { realmName: "Spinebreaker" },
  { realmName: "Spirestone" },
  { realmName: "Staghelm" },
  { realmName: "Steamwheedle Cartel" },
  { realmName: "Stormrage" },
  { realmName: "Stormreaver" },
  { realmName: "Stormscale" },
  { realmName: "Suramar" },
  { realmName: "Tanaris" },
  { realmName: "Terokkar" },
  { realmName: "Terenas" },
  { realmName: "The Forgotten Coast" },
  { realmName: "The Scryers" },
  { realmName: "The Underbog" },
  { realmName: "The Venture Co" },
  { realmName: "Thorium Brotherhood" },
  { realmName: "Thrall" },
  { realmName: "Thunderhorn" },
  { realmName: "Thunderlord" },
  { realmName: "Tichondrius" },
  { realmName: "Tol Barad" },
  { realmName: "Tortheldrin" },
  { realmName: "Trollbane" },
  { realmName: "Turalyon" },
  { realmName: "Twisting Nether" },
  { realmName: "Uldaman" },
  { realmName: "Undermine" },
  { realmName: "Ursin" },
  { realmName: "Uther" },
  { realmName: "Vashj" },
  { realmName: "Vek'nilash" },
  { realmName: "Velen" },
  { realmName: "Venture Co" },
  { realmName: "Warsong" },
  { realmName: "Warsong Gulch" },
  { realmName: "Whisperwind" },
  { realmName: "Wildhammer" },
  { realmName: "Windrunner" },
  { realmName: "Winterhoof" },
  { realmName: "World Tree" },
  { realmName: "Ysera" },
  { realmName: "Ysondre" },
  { realmName: "Zandalar Tribe" },
  { realmName: "Zangarmarsh" },
  { realmName: "Zuluhed" },
  { realmName: "Zul'jin" }
];
