// search for regions with ctrl + f (terms: KR, TW, EU, US)

export const realms = [
  // KR Realms
  { name: "Realm Status", region: "kr" },
  { name: "Alexstrasza", region: "kr" },
  { name: "Azshara", region: "kr" },
  { name: "Burning Legion", region: "kr" },
  { name: "Cenarius", region: "kr" },
  { name: "Dalaran", region: "kr" },
  { name: "Deathwing", region: "kr" },
  { name: "Durotan", region: "kr" },
  { name: "Garona", region: "kr" },
  { name: "Gul'dan", region: "kr" },
  { name: "Hellscream", region: "kr" },
  { name: "Hyjal", region: "kr" },
  { name: "Malfurion", region: "kr" },
  { name: "Norgannon", region: "kr" },
  { name: "Rexxar", region: "kr" },
  { name: "Stormrage", region: "kr" },
  { name: "Wildhammer", region: "kr" },
  { name: "Windrunner", region: "kr" },
  { name: "Zul'jin", region: "kr" },
  
  // TW Realms
  { name: "Arthas", region: "tw" },
  { name: "Arygos", region: "tw" },
  { name: "Bleeding Hollow", region: "tw" },
  { name: "Chillwind Point", region: "tw" },
  { name: "Crystalpine Stinger", region: "tw" },
  { name: "Demon Fall Canyon", region: "tw" },
  { name: "Dragonmaw", region: "tw" },
  { name: "Frostmane", region: "tw" },
  { name: "Hellscream", region: "tw" },
  { name: "Icecrown", region: "tw" },
  { name: "Krol Blade", region: "tw" },
  { name: "Light's Hope", region: "tw" },
  { name: "Menethil", region: "tw" },
  { name: "Nightsong", region: "tw" },
  { name: "Old Blanchy", region: "tw" },
  { name: "Order of the Cloud Serpent", region: "tw" },
  { name: "Quel'dorei", region: "tw" },
  { name: "Shadowmoon", region: "tw" },
  { name: "Silverwing Hold", region: "tw" },
  { name: "Skywall", region: "tw" },
  { name: "Spirestone", region: "tw" },
  { name: "Stormscale", region: "tw" },
  { name: "Sundown Marsh", region: "tw" },
  { name: "Whisperwind", region: "tw" },
  { name: "World Tree", region: "tw" },
  { name: "Wrathbringer", region: "tw" },
  { name: "Zealot Blade", region: "tw" },

  // EU Realms
  { name: "Aegwynn", region: "eu" },
  { name: "Aerie Peak", region: "eu" },
  { name: "Agamaggan", region: "eu" },
  { name: "Aggra (Português)", region: "eu" },
  { name: "Aggramar", region: "eu" },
  { name: "Ahn'Qiraj", region: "eu" },
  { name: "Al'Akir", region: "eu" },
  { name: "Alexstrasza", region: "eu" },
  { name: "Alleria", region: "eu" },
  { name: "Alonsus", region: "eu" },
  { name: "Aman'Thul", region: "eu" },
  { name: "Ambossar", region: "eu" },
  { name: "Anachronos", region: "eu" },
  { name: "Anetheron", region: "eu" },
  { name: "Antonidas", region: "eu" },
  { name: "Anub'arak", region: "eu" },
  { name: "Arak-arahm", region: "eu" },
  { name: "Arathi", region: "eu" },
  { name: "Arathor", region: "eu" },
  { name: "Archimonde", region: "eu" },
  { name: "Area 52", region: "eu" },
  { name: "Argent Dawn", region: "eu" },
  { name: "Arthas", region: "eu" },
  { name: "Arygos", region: "eu" },
  { name: "Ashenvale", region: "eu" },
  { name: "Aszune", region: "eu" },
  { name: "Auchindoun", region: "eu" },
  { name: "Azjol-Nerub", region: "eu" },
  { name: "Azshara", region: "eu" },
  { name: "Azuregos", region: "eu" },
  { name: "Azuremyst", region: "eu" },
  { name: "Baelgun", region: "eu" },
  { name: "Balnazzar", region: "eu" },
  { name: "Blackhand", region: "eu" },
  { name: "Blackmoore", region: "eu" },
  { name: "Blackrock", region: "eu" },
  { name: "Blackscar", region: "eu" },
  { name: "Blade's Edge", region: "eu" },
  { name: "Bladefist", region: "eu" },
  { name: "Bloodfeather", region: "eu" },
  { name: "Bloodhoof", region: "eu" },
  { name: "Bloodscalp", region: "eu" },
  { name: "Blutkessel", region: "eu" },
  { name: "Booty Bay", region: "eu" },
  { name: "Borean Tundra", region: "eu" },
  { name: "Boulderfist", region: "eu" },
  { name: "Bronze Dragonflight", region: "eu" },
  { name: "Bronzebeard", region: "eu" },
  { name: "Burning Blade", region: "eu" },
  { name: "Burning Legion", region: "eu" },
  { name: "Burning Steppes", region: "eu" },
  { name: "C'Thun", region: "eu" },
  { name: "Chamber of Aspects", region: "eu" },
  { name: "Chants éternels", region: "eu" },
  { name: "Cho'gall", region: "eu" },
  { name: "Chromaggus", region: "eu" },
  { name: "Colinas Pardas", region: "eu" },
  { name: "Confrérie du Thorium", region: "eu" },
  { name: "Conseil des Ombres", region: "eu" },
  { name: "Crushridge", region: "eu" },
  { name: "Culte de la Rive noire", region: "eu" },
  { name: "Daggerspine", region: "eu" },
  { name: "Dalaran", region: "eu" },
  { name: "Dalvengyr", region: "eu" },
  { name: "Darkmoon Faire", region: "eu" },
  { name: "Darksorrow", region: "eu" },
  { name: "Darkspear", region: "eu" },
  { name: "Das Konsortium", region: "eu" },
  { name: "Das Syndikat", region: "eu" },
  { name: "Deathguard", region: "eu" },
  { name: "Deathweaver", region: "eu" },
  { name: "Deathwing", region: "eu" },
  { name: "Deepholm", region: "eu" },
  { name: "Defias Brotherhood", region: "eu" },
  { name: "Dentarg", region: "eu" },
  { name: "Der Mithrilorden", region: "eu" },
  { name: "Der Rat von Dalaran", region: "eu" },
  { name: "Der abyssische Rat", region: "eu" },
  { name: "Destromath", region: "eu" },
  { name: "Dethecus", region: "eu" },
  { name: "Die Aldor", region: "eu" },
  { name: "Die Arguswacht", region: "eu" },
  { name: "Die Nachtwache", region: "eu" },
  { name: "Die Silberne Hand", region: "eu" },
  { name: "Die Todeskrallen", region: "eu" },
  { name: "Die ewige Wacht", region: "eu" },
  { name: "Doomhammer", region: "eu" },
  { name: "Draenor", region: "eu" },
  { name: "Dragonblight", region: "eu" },
  { name: "Dragonmaw", region: "eu" },
  { name: "Drak'thul", region: "eu" },
  { name: "Drek'Thar", region: "eu" },
  { name: "Dun Modr", region: "eu" },
  { name: "Dun Morogh", region: "eu" },
  { name: "Dunemaul", region: "eu" },
  { name: "Durotan", region: "eu" },
  { name: "Earthen Ring", region: "eu" },
  { name: "Echsenkessel", region: "eu" },
  { name: "Eitrigg", region: "eu" },
  { name: "Eldre'Thalas", region: "eu" },
  { name: "Elune", region: "eu" },
  { name: "Emerald Dream", region: "eu" },
  { name: "Emeriss", region: "eu" },
  { name: "Eonar", region: "eu" },
  { name: "Eredar", region: "eu" },
  { name: "Eversong", region: "eu" },
  { name: "Executus", region: "eu" },
  { name: "Exodar", region: "eu" },
  { name: "Festung der Stürme", region: "eu" },
  { name: "Fordragon", region: "eu" },
  { name: "Forscherliga", region: "eu" },
  { name: "Frostmane", region: "eu" },
  { name: "Frostmourne", region: "eu" },
  { name: "Frostwhisper", region: "eu" },
  { name: "Frostwolf", region: "eu" },
  { name: "Galakrond", region: "eu" },
  { name: "Garona", region: "eu" },
  { name: "Garrosh", region: "eu" },
  { name: "Genjuros", region: "eu" },
  { name: "Ghostlands", region: "eu" },
  { name: "Gilneas", region: "eu" },
  { name: "Goldrinn", region: "eu" },
  { name: "Gordunni", region: "eu" },
  { name: "Gorgonnash", region: "eu" },
  { name: "Greymane", region: "eu" },
  { name: "Grim Batol", region: "eu" },
  { name: "Grom", region: "eu" },
  { name: "Gul'dan", region: "eu" },
  { name: "Hakkar", region: "eu" },
  { name: "Haomarush", region: "eu" },
  { name: "Hellfire", region: "eu" },
  { name: "Hellscream", region: "eu" },
  { name: "Howling Fjord", region: "eu" },
  { name: "Hyjal", region: "eu" },
  { name: "Illidan", region: "eu" },
  { name: "Jaedenar", region: "eu" },
  { name: "Kael'thas", region: "eu" },
  { name: "Karazhan", region: "eu" },
  { name: "Kargath", region: "eu" },
  { name: "Kazzak", region: "eu" },
  { name: "Kel'Thuzad", region: "eu" },
  { name: "Khadgar", region: "eu" },
  { name: "Khaz Modan", region: "eu" },
  { name: "Khaz'goroth", region: "eu" },
  { name: "Kil'jaeden", region: "eu" },
  { name: "Kilrogg", region: "eu" },
  { name: "Kirin Tor", region: "eu" },
  { name: "Kor'gall", region: "eu" },
  { name: "Krag'jin", region: "eu" },
  { name: "Krasus", region: "eu" },
  { name: "Kul Tiras", region: "eu" },
  { name: "Kult der Verdammten", region: "eu" },
  { name: "La Croisade écarlate", region: "eu" },
  { name: "Laughing Skull", region: "eu" },
  { name: "Les Clairvoyants", region: "eu" },
  { name: "Les Sentinelles", region: "eu" },
  { name: "Lich King", region: "eu" },
  { name: "Lightbringer", region: "eu" },
  { name: "Lightning's Blade", region: "eu" },
  { name: "Lordaeron", region: "eu" },
  { name: "Los Errantes", region: "eu" },
  { name: "Lothar", region: "eu" },
  { name: "Madmortem", region: "eu" },
  { name: "Magtheridon", region: "eu" },
  { name: "Mal'Ganis", region: "eu" },
  { name: "Malfurion", region: "eu" },
  { name: "Malorne", region: "eu" },
  { name: "Malygos", region: "eu" },
  { name: "Mannoroth", region: "eu" },
  { name: "Marécage de Zangar", region: "eu" },
  { name: "Mazrigos", region: "eu" },
  { name: "Medivh", region: "eu" },
  { name: "Minahonda", region: "eu" },
  { name: "Moonglade", region: "eu" },
  { name: "Mug'thol", region: "eu" },
  { name: "Nagrand", region: "eu" },
  { name: "Nathrezim", region: "eu" },
  { name: "Naxxramas", region: "eu" },
  { name: "Nazjatar", region: "eu" },
  { name: "Nefarian", region: "eu" },
  { name: "Nemesis", region: "eu" },
  { name: "Neptulon", region: "eu" },
  { name: "Ner'zhul", region: "eu" },
  { name: "Nera'thor", region: "eu" },
  { name: "Nethersturm", region: "eu" },
  { name: "Nordrassil", region: "eu" },
  { name: "Norgannon", region: "eu" },
  { name: "Nozdormu", region: "eu" },
  { name: "Onyxia", region: "eu" },
  { name: "Outland", region: "eu" },
  { name: "Perenolde", region: "eu" },
  { name: "Pozzo dell'Eternità", region: "eu" },
  { name: "Proudmoore", region: "eu" },
  { name: "Quel'Thalas", region: "eu" },
  { name: "Ragnaros", region: "eu" },
  { name: "Rajaxx", region: "eu" },
  { name: "Rashgarroth", region: "eu" },
  { name: "Ravencrest", region: "eu" },
  { name: "Ravenholdt", region: "eu" },
  { name: "Razuvious", region: "eu" },
  { name: "Rexxar", region: "eu" },
  { name: "Runetotem", region: "eu" },
  { name: "Sanguino", region: "eu" },
  { name: "Sargeras", region: "eu" },
  { name: "Saurfang", region: "eu" },
  { name: "Scarshield Legion", region: "eu" },
  { name: "Sen'jin", region: "eu" },
  { name: "Shadowsong", region: "eu" },
  { name: "Shattered Halls", region: "eu" },
  { name: "Shattered Hand", region: "eu" },
  { name: "Shattrath", region: "eu" },
  { name: "Shen'dralar", region: "eu" },
  { name: "Silvermoon", region: "eu" },
  { name: "Sinstralis", region: "eu" },
  { name: "Skullcrusher", region: "eu" },
  { name: "Soulflayer", region: "eu" },
  { name: "Spinebreaker", region: "eu" },
  { name: "Sporeggar", region: "eu" },
  { name: "Steamwheedle Cartel", region: "eu" },
  { name: "Stormrage", region: "eu" },
  { name: "Stormreaver", region: "eu" },
  { name: "Stormscale", region: "eu" },
  { name: "Sunstrider", region: "eu" },
  { name: "Suramar", region: "eu" },
  { name: "Sylvanas", region: "eu" },
  { name: "Taerar", region: "eu" },
  { name: "Talnivarr", region: "eu" },
  { name: "Tarren Mill", region: "eu" },
  { name: "Teldrassil", region: "eu" },
  { name: "Temple noir", region: "eu" },
  { name: "Terenas", region: "eu" },
  { name: "Terokkar", region: "eu" },
  { name: "Terrordar", region: "eu" },
  { name: "The Maelstrom", region: "eu" },
  { name: "The Sha'tar", region: "eu" },
  { name: "The Venture Co", region: "eu" },
  { name: "Theradras", region: "eu" },
  { name: "Thermaplugg", region: "eu" },
  { name: "Thrall", region: "eu" },
  { name: "Throk'Feroth", region: "eu" },
  { name: "Thunderhorn", region: "eu" },
  { name: "Tichondrius", region: "eu" },
  { name: "Tirion", region: "eu" },
  { name: "Todeswache", region: "eu" },
  { name: "Trollbane", region: "eu" },
  { name: "Turalyon", region: "eu" },
  { name: "Twilight's Hammer", region: "eu" },
  { name: "Twisting Nether", region: "eu" },
  { name: "Tyrande", region: "eu" },
  { name: "Uldaman", region: "eu" },
  { name: "Ulduar", region: "eu" },
  { name: "Uldum", region: "eu" },
  { name: "Un'Goro", region: "eu" },
  { name: "Varimathras", region: "eu" },
  { name: "Vashj", region: "eu" },
  { name: "Vek'lor", region: "eu" },
  { name: "Vek'nilash", region: "eu" },
  { name: "Vol'jin", region: "eu" },
  { name: "Wildhammer", region: "eu" },
  { name: "Wrathbringer", region: "eu" },
  { name: "Xavius", region: "eu" },
  { name: "Ysera", region: "eu" },
  { name: "Ysondre", region: "eu" },
  { name: "Zenedar", region: "eu" },
  { name: "Zirkel des Cenarius", region: "eu" },
  { name: "Zul'jin", region: "eu" },
  { name: "Zuluhed", region: "eu" },

  // US Realms
  { name: "Aegwynn", region: "us" },
  { name: "Aerie Peak", region: "us" },
  { name: "Agamaggan", region: "us" },
  { name: "Aggramar", region: "us" },
  { name: "Akama", region: "us" },
  { name: "Alexstrasza", region: "us" },
  { name: "Alleria", region: "us" },
  { name: "Altar of Storms", region: "us" },
  { name: "Alterac Mountains", region: "us" },
  { name: "Aman'Thul", region: "us" },
  { name: "Andorhal", region: "us" },
  { name: "Anetheron", region: "us" },
  { name: "Antonidas", region: "us" },
  { name: "Anub'arak", region: "us" },
  { name: "Anvilmar", region: "us" },
  { name: "Arathor", region: "us" },
  { name: "Archimonde", region: "us" },
  { name: "Area 52", region: "us" },
  { name: "Argent Dawn", region: "us" },
  { name: "Arthas", region: "us" },
  { name: "Arygos", region: "us" },
  { name: "Auchindoun", region: "us" },
  { name: "Azgalor", region: "us" },
  { name: "Azjol-Nerub", region: "us" },
  { name: "Azralon", region: "us" },
  { name: "Azshara", region: "us" },
  { name: "Azuremyst", region: "us" },
  { name: "Baelgun", region: "us" },
  { name: "Balnazzar", region: "us" },
  { name: "Barthilas", region: "us" },
  { name: "Black Dragonflight", region: "us" },
  { name: "Blackhand", region: "us" },
  { name: "Blackrock", region: "us" },
  { name: "Blackwater Raiders", region: "us" },
  { name: "Blackwing Lair", region: "us" },
  { name: "Blade's Edge", region: "us" },
  { name: "Bladefist", region: "us" },
  { name: "Bleeding Hollow", region: "us" },
  { name: "Blood Furnace", region: "us" },
  { name: "Bloodhoof", region: "us" },
  { name: "Bloodscalp", region: "us" },
  { name: "Bonechewer", region: "us" },
  { name: "Borean Tundra", region: "us" },
  { name: "Boulderfist", region: "us" },
  { name: "Bronzebeard", region: "us" },
  { name: "Burning Blade", region: "us" },
  { name: "Burning Legion", region: "us" },
  { name: "Caelestrasz", region: "us" },
  { name: "Cairne", region: "us" },
  { name: "Cenarion Circle", region: "us" },
  { name: "Cenarius", region: "us" },
  { name: "Cho'gall", region: "us" },
  { name: "Chromaggus", region: "us" },
  { name: "Coilfang", region: "us" },
  { name: "Crushridge", region: "us" },
  { name: "Daggerspine", region: "us" },
  { name: "Dalaran", region: "us" },
  { name: "Dalvengyr", region: "us" },
  { name: "Dark Iron", region: "us" },
  { name: "Darkspear", region: "us" },
  { name: "Darrowmere", region: "us" },
  { name: "Dath'Remar", region: "us" },
  { name: "Dawnbringer", region: "us" },
  { name: "Deathwing", region: "us" },
  { name: "Demon Soul", region: "us" },
  { name: "Dentarg", region: "us" },
  { name: "Destromath", region: "us" },
  { name: "Dethecus", region: "us" },
  { name: "Detheroc", region: "us" },
  { name: "Doomhammer", region: "us" },
  { name: "Draenor", region: "us" },
  { name: "Dragonblight", region: "us" },
  { name: "Dragonmaw", region: "us" },
  { name: "Drak'Tharon", region: "us" },
  { name: "Drak'thul", region: "us" },
  { name: "Draka", region: "us" },
  { name: "Drakkari", region: "us" },
  { name: "Dreadmaul", region: "us" },
  { name: "Drenden", region: "us" },
  { name: "Dunemaul", region: "us" },
  { name: "Durotan", region: "us" },
  { name: "Duskwood", region: "us" },
  { name: "Earthen Ring", region: "us" },
  { name: "Echo Isles", region: "us" },
  { name: "Eitrigg", region: "us" },
  { name: "Eldre'Thalas", region: "us" },
  { name: "Elune", region: "us" },
  { name: "Emerald Dream", region: "us" },
  { name: "Eonar", region: "us" },
  { name: "Eredar", region: "us" },
  { name: "Executus", region: "us" },
  { name: "Exodar", region: "us" },
  { name: "Farstriders", region: "us" },
  { name: "Feathermoon", region: "us" },
  { name: "Fenris", region: "us" },
  { name: "Firetree", region: "us" },
  { name: "Fizzcrank", region: "us" },
  { name: "Frostmane", region: "us" },
  { name: "Frostmourne", region: "us" },
  { name: "Frostwolf", region: "us" },
  { name: "Galakrond", region: "us" },
  { name: "Gallywix", region: "us" },
  { name: "Garithos", region: "us" },
  { name: "Garona", region: "us" },
  { name: "Garrosh", region: "us" },
  { name: "Ghostlands", region: "us" },
  { name: "Gilneas", region: "us" },
  { name: "Gnomeregan", region: "us" },
  { name: "Goldrinn", region: "us" },
  { name: "Gorefiend", region: "us" },
  { name: "Gorgonnash", region: "us" },
  { name: "Greymane", region: "us" },
  { name: "Grizzly Hills", region: "us" },
  { name: "Gul'dan", region: "us" },
  { name: "Gundrak", region: "us" },
  { name: "Gurubashi", region: "us" },
  { name: "Hakkar", region: "us" },
  { name: "Haomarush", region: "us" },
  { name: "Hellscream", region: "us" },
  { name: "Hydraxis", region: "us" },
  { name: "Hyjal", region: "us" },
  { name: "Icecrown", region: "us" },
  { name: "Illidan", region: "us" },
  { name: "Jaedenar", region: "us" },
  { name: "Jubei'Thos", region: "us" },
  { name: "Kael'thas", region: "us" },
  { name: "Kalecgos", region: "us" },
  { name: "Kargath", region: "us" },
  { name: "Kel'Thuzad", region: "us" },
  { name: "Khadgar", region: "us" },
  { name: "Khaz Modan", region: "us" },
  { name: "Khaz'goroth", region: "us" },
  { name: "Kil'jaeden", region: "us" },
  { name: "Kilrogg", region: "us" },
  { name: "Kirin Tor", region: "us" },
  { name: "Korgath", region: "us" },
  { name: "Korialstrasz", region: "us" },
  { name: "Kul Tiras", region: "us" },
  { name: "Laughing Skull", region: "us" },
  { name: "Lethon", region: "us" },
  { name: "Lightbringer", region: "us" },
  { name: "Lightning's Blade", region: "us" },
  { name: "Lightninghoof", region: "us" },
  { name: "Llane", region: "us" },
  { name: "Lothar", region: "us" },
  { name: "Madoran", region: "us" },
  { name: "Maelstrom", region: "us" },
  { name: "Magtheridon", region: "us" },
  { name: "Maiev", region: "us" },
  { name: "Mal'Ganis", region: "us" },
  { name: "Malfurion", region: "us" },
  { name: "Malorne", region: "us" },
  { name: "Malygos", region: "us" },
  { name: "Mannoroth", region: "us" },
  { name: "Medivh", region: "us" },
  { name: "Misha", region: "us" },
  { name: "Mok'Nathal", region: "us" },
  { name: "Moon Guard", region: "us" },
  { name: "Moonrunner", region: "us" },
  { name: "Mug'thol", region: "us" },
  { name: "Muradin", region: "us" },
  { name: "Nagrand", region: "us" },
  { name: "Nathrezim", region: "us" },
  { name: "Nazgrel", region: "us" },
  { name: "Nazjatar", region: "us" },
  { name: "Nemesis", region: "us" },
  { name: "Ner'zhul", region: "us" },
  { name: "Nesingwary", region: "us" },
  { name: "Nordrassil", region: "us" },
  { name: "Norgannon", region: "us" },
  { name: "Onyxia", region: "us" },
  { name: "Perenolde", region: "us" },
  { name: "Proudmoore", region: "us" },
  { name: "Quel'Thalas", region: "us" },
  { name: "Quel'dorei", region: "us" },
  { name: "Ragnaros", region: "us" },
  { name: "Ravencrest", region: "us" },
  { name: "Ravenholdt", region: "us" },
  { name: "Rexxar", region: "us" },
  { name: "Rivendare", region: "us" },
  { name: "Runetotem", region: "us" },
  { name: "Sargeras", region: "us" },
  { name: "Saurfang", region: "us" },
  { name: "Scarlet Crusade", region: "us" },
  { name: "Scilla", region: "us" },
  { name: "Sen'jin", region: "us" },
  { name: "Sentinels", region: "us" },
  { name: "Shadow Council", region: "us" },
  { name: "Shadowmoon", region: "us" },
  { name: "Shadowsong", region: "us" },
  { name: "Shandris", region: "us" },
  { name: "Shattered Halls", region: "us" },
  { name: "Shattered Hand", region: "us" },
  { name: "Shu'halo", region: "us" },
  { name: "Silver Hand", region: "us" },
  { name: "Silvermoon", region: "us" },
  { name: "Sisters of Elune", region: "us" },
  { name: "Skullcrusher", region: "us" },
  { name: "Skywall", region: "us" },
  { name: "Smolderthorn", region: "us" },
  { name: "Spinebreaker", region: "us" },
  { name: "Spirestone", region: "us" },
  { name: "Staghelm", region: "us" },
  { name: "Steamwheedle Cartel", region: "us" },
  { name: "Stonemaul", region: "us" },
  { name: "Stormrage", region: "us" },
  { name: "Stormreaver", region: "us" },
  { name: "Stormscale", region: "us" },
  { name: "Suramar", region: "us" },
  { name: "Tanaris", region: "us" },
  { name: "Terenas", region: "us" },
  { name: "Terokkar", region: "us" },
  { name: "Thaurissan", region: "us" },
  { name: "The Forgotten Coast", region: "us" },
  { name: "The Scryers", region: "us" },
  { name: "The Underbog", region: "us" },
  { name: "The Venture Co", region: "us" },
  { name: "Thorium Brotherhood", region: "us" },
  { name: "Thrall", region: "us" },
  { name: "Thunderhorn", region: "us" },
  { name: "Thunderlord", region: "us" },
  { name: "Tichondrius", region: "us" },
  { name: "Tol Barad", region: "us" },
  { name: "Tortheldrin", region: "us" },
  { name: "Trollbane", region: "us" },
  { name: "Turalyon", region: "us" },
  { name: "Twisting Nether", region: "us" },
  { name: "Uldaman", region: "us" },
  { name: "Uldum", region: "us" },
  { name: "Undermine", region: "us" },
  { name: "Ursin", region: "us" },
  { name: "Uther", region: "us" },
  { name: "Vashj", region: "us" },
  { name: "Vek'nilash", region: "us" },
  { name: "Velen", region: "us" },
  { name: "Warsong", region: "us" },
  { name: "Whisperwind", region: "us" },
  { name: "Wildhammer", region: "us" },
  { name: "Windrunner", region: "us" },
  { name: "Winterhoof", region: "us" },
  { name: "Wyrmrest Accord", region: "us" },
  { name: "Ysera", region: "us" },
  { name: "Ysondre", region: "us" },
  { name: "Zangarmarsh", region: "us" },
  { name: "Zul'jin", region: "us" },
  { name: "Zuluhed", region: "us" },


]